site_name:        PhyloNetworks.jl
repo_url:         https://github.com/crsl4/PhyloNetworks.jl
site_description: PhyloNetworks is a Julia package for the manipulation, visualization and inference of phylogenetic networks.
site_author:      Claudia Sol&iacute;s-Lemus

theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent:  'teal'
  logo: 'snaq_small.png'

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math
  - codehilite

docs_dir: 'build'

pages:
  - Home: index.md
  - Manual:
    - Installation: man/installation.md
    - Input Data for SNaQ: man/inputdata.md
    - TICR pipeline: man/ticr_howtogetQuartetCFs.md
    # - Network estimation and display: man/snaq_plot.md
    - Network comparison and manipulation: man/dist_reroot.md
    - Candidate Networks: man/fixednetworkoptim.md
    # - Extract Expected CFs: man/expectedCFs.md
    - Bootstrap: man/bootstrap.md
    - Multiple Alleles: man/multiplealleles.md
    - Continuous Trait Evolution: man/trait_tree.md
  - Library:
    - Public: lib/public.md
    - Internals: lib/internals.md
